source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  panes:
    path: panes
    output: true
    description: ''
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/pane.html
        reorder_inputs: false
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
data_config: {}
timezone: Etc/UTC
