source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  panes:
    path: panes
    output: true
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      pane:
        path: .cloudcannon/schemas/pane.md
        reorder_inputs: false
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name:
        icon: notes
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
data_config: {}
timezone: Etc/UTC
